services:
  - type: web
    name: fake-artist-backend
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://fake-artist-phi.vercel.app
    autoDeploy: true
